on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      gcp-get-all-clients-endpoint:
        required: false
        type: string
      gcp-get-all-clients-username:
        required: false
        type: string
      gcp-get-all-clients-password:
        required: false
        type: string
    secrets:
      dev-hub-auth-url:
        required: true
jobs:
  feature-test-robot:
    name: "Feature Test - Robot"
    runs-on: ubuntu-latest
    steps:
      - uses: smokushka/feature-test-robot@v2
        with:
          dev-hub-auth-url: "${{ secrets.dev-hub-auth-url }}"
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
    env:
      GCP_GET_ALL_CLIENTS_ENDPOINT_DEV: ${{ inputs.gcp-get-all-clients-endpoint }}
      GCP_GET_ALL_CLIENTS_USERNAME_DEV: ${{ inputs.gcp-get-all-clients-username }}
      GCP_GET_ALL_CLIENTS_PASSWORD_DEV: ${{ inputs.gcp-get-all-clients-password }}
  build-feature-test-package:
    name: "Build Feature Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: smokushka/build-feature-test-package@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
  feature-test-2gp:
    name: "Feature Test - 2GP"
    runs-on: ubuntu-latest
    needs:
      - build-feature-test-package
    steps:
      - uses: smokushka/feature-test-2gp@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
  qa-test:
    name: "QA Test"
    runs-on: ubuntu-latest
    needs:
      - build-feature-test-package
    steps:
      - uses: Smokushka/qa-test@main
        with:
          dev-hub-auth-url: "${{ secrets.dev-hub-auth-url }}"
          org-name: "beta"
          cumulusci-version: "3.77.0"
